<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Currency switcher
 *
 * @var \Magento\Directory\Block\Currency $block
 */

?>
<?php if ($block->getCurrencyCount() > 1) : ?>
	<?php $currencies = $block->getCurrencies(); ?>
    <?php $currentCurrencyCode = $block->getCurrentCurrencyCode(); ?>
    <?php $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : '' ?>
	<div class="block block-currency" id="switcher-currency<?= $block->escapeHtmlAttr($id) ?>">
		
		<div class="item-cur language-<?= $block->escapeHtml($block->getCurrentCurrencyCode()) ?>">
			<span><?= $block->escapeHtml($currentCurrencyCode) ?></span> <i class="fa fa-angle-down"></i>
		</div>
			<ul>
				<?php foreach ($currencies as $_code => $_name) : ?>
                    <?php if ($_code != $currentCurrencyCode) : ?>
						<li> <a href="#" data-post='<?= /* @noEscape */ $block->getSwitchCurrencyPostData($_code) ?>'>
						<span class="cur_icon">€</span><?= $block->escapeHtml($_code) ?></a>
						</li>
						
						<!--<li> <a class="selected" href="#"><span class="cur_icon">$</span> USD</a></li>-->
					<?php endif; ?>
                <?php endforeach; ?>
			</ul>
	</div>
<?php endif; ?>